# Generated by Django 3.0.5 on 2020-05-10 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_no', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('state_no', models.AutoField(primary_key=True, serialize=False)),
                ('state_name', models.CharField(max_length=50, unique=True)),
                ('state_country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app19.Country')),
            ],
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('city_no', models.AutoField(primary_key=True, serialize=False)),
                ('city_name', models.CharField(max_length=50, unique=True)),
                ('city_state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app19.State')),
            ],
        ),
    ]
