# Generated by Django 3.0.5 on 2020-05-11 06:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_idno', models.AutoField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=30)),
                ('employee_salary', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('payment_no', models.AutoField(primary_key=True, serialize=False)),
                ('payment_amount', models.FloatField()),
                ('payment_employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='app20.Employee')),
            ],
        ),
    ]
