# Generated by Django 3.0.5 on 2020-05-11 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app20', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(default=None),
        ),
    ]
