# Generated by Django 3.0.5 on 2020-05-22 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app29', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LanguagesModel',
            fields=[
                ('no', models.AutoField(primary_key=True, serialize=False)),
                ('language_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='employeemodel',
            name='langs',
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='langs',
            field=models.ManyToManyField(default=None, to='app29.LanguagesModel'),
        ),
    ]
