# Generated by Django 3.0.5 on 2020-05-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('idno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('salary', models.FloatField()),
                ('photo', models.ImageField(upload_to='employee_images/')),
            ],
        ),
    ]
