# Generated by Django 3.1.4 on 2021-06-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=100)),
                ('p_price', models.IntegerField()),
                ('p_photo', models.ImageField(upload_to='product_images/')),
            ],
        ),
    ]
