# Generated by Django 3.1.4 on 2021-06-12 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_name', models.CharField(max_length=40)),
                ('emp_salary', models.FloatField()),
                ('emp_degn', models.CharField(max_length=30)),
                ('emp_photo', models.ImageField(upload_to='emp_images/')),
            ],
        ),
    ]
