# Generated by Django 3.0.5 on 2020-05-08 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CourseModel',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=50, unique=True)),
                ('course_fee', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_name', models.CharField(max_length=50)),
                ('student_contactno', models.IntegerField(unique=True)),
                ('student_courses', models.ManyToManyField(to='app18.CourseModel')),
            ],
        ),
    ]
